---
title: "xinru_data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(truncnorm)
library(tidyverse)
```

## weijia's

```{r}
T=1460
latent_class=2
## when the state in time point t is 1, the probability of next point equals to 1 is 0.8
p=cbind(c(0.8,0.2),c(0.2,0.8))
sd=0.5

## latent state
set.seed(1)
z=rep(NA,T)
z[1]=1
for(t in 1:(T-1)){
  z[t+1]=sample(1:latent_class,size = 1,prob = p[z[t],])
}

## simulate the input data
call_counts=rpois(T,3)
text_counts=rpois(T,6)

## simulate the outcome data
p_2=c(0.3,0.7)
rmultinom(n=3,size = 3,prob = p_2)
```

## update version

```{r}
T=1460
latent_class=2
## generate transition matrix between latent state
set.seed(1)
m_1=round(rtruncnorm(n=T-3, a=0, b=1, mean=0.7, sd=0.1),2)     
set.seed(1)
m_2=round(rtruncnorm(n=T-3, a=0, b=1, mean=0.3, sd=0.1),2)


m_3=1-m_1
m_4=1-m_2
p=as.list(rep(NA,T-3))
i=1
for (i in 1:(T-3)) {
  p[[i]] = cbind(c(m_1[i],m_2[i]),c(m_3[i],m_4[i]))
}

sd=0.5

## latent state
set.seed(1)
z=rep(NA,T)
z[1]=1
z[2]=1
z[3]=1
my_prob=rep(NULL,2)
for(t in 1:(T-3)){
  z_mean=round((z[t]+z[t+1]+z[t+2])/3)
  my_prob=rbind(my_prob,p[[t]][z_mean,])
  z[t+3]=sample(1:latent_class,size = 1,prob = my_prob[t,])
}

initial_call_counts=c(3,5,6)
initial_text_counts=c(3,5,6)
initial_duration=c(3,5,6)
## simulate the input data
## the call counts are determined by the probability of latent disease status of that day point
set.seed(1)
call_counts=c(initial_call_counts,rpois(T-3,round(7*my_prob[,2])))
set.seed(1)
text_counts=c(initial_text_counts,rpois(T-3,round(5*my_prob[,2])))
set.seed(1)
duration=c(initial_duration,round(rtruncnorm(n=T-3, a=0, b=10, mean=10*my_prob[,2], sd=2)))

## simulate the outcome data
i=1
## set the initial prob
class_prob=c(0.3,0.4,0.5)
for(i in 1:(T-3)){
  class_prob=c(class_prob,my_prob[i,2])
}

set.seed(1)
p_2=as.list(rep(NA,T))
i=1
for (i in 1:T) {
  class_2_prob=rtruncnorm(n=1,a=0,b=1,mean=class_prob[i],sd=0.05)
  p_2[[i]] = c((1-class_2_prob),class_2_prob)
}

i=1
survey_outcome=NULL
set.seed(1)
for (i in 1:T) {
  survey_outcome=cbind(survey_outcome,rmultinom(n=1,size = 3,prob = p_2[[i]]))
}


survey_outcome=survey_outcome[1,]*1+survey_outcome[2,]*2

complete_data=as.data.frame(cbind(call_counts,text_counts,duration,survey_outcome,z)) %>% 
  mutate(
    day=1:1460
  )

## when latent state is 1
sub_1=complete_data[which(z==1),]
## when latent state is 2
sub_2=complete_data[which(z==2),]

par(mfrow = c(1, 2)) 
## when latent state is 2, the survey outcome will be larger
plot(density(sub_1$survey_outcome),xlab = "",main = "Density of survey score when latent state is nondisease",cex.main=0.7,cex.lab=0.7,cex.axis=0.7)
lines(x=c(mean(sub_1$survey_outcome),mean(sub_1$survey_outcome)),y=c(-0.5,0.6),col="red",lty=2)
plot(density(sub_2$survey_outcome),xlab = "",main = "Density of survey score when latent state is disease",cex.main=0.7,cex.lab=0.7,cex.axis=0.7)
lines(x=c(mean(sub_2$survey_outcome),mean(sub_2$survey_outcome)),y=c(-0.5,0.6),col="red",lty=2)

par(mfrow = c(3, 2)) 
## when latent state is 2, the call counts will be larger
plot(density(sub_1$call_counts),xlab = "",main = "Density of call counts when latent state is nondisease",cex.main=0.7,cex.lab=0.7,cex.axis=0.7)
lines(x=c(mean(sub_1$call_counts),mean(sub_1$call_counts)),y=c(-0.5,0.6),col="red",lty=2)
plot(density(sub_2$call_counts),xlab = "",main = "Density of call counts when latent state is disease",cex.main=0.7,cex.lab=0.7,cex.axis=0.7)
lines(x=c(mean(sub_2$call_counts),mean(sub_2$call_counts)),y=c(-0.5,0.6),col="red",lty=2)

## when latent state is 2, the text counts will be larger
plot(density(sub_1$text_counts),xlab = "",main = "Density of text counts when latent state is nondisease",cex.main=0.7,cex.lab=0.7,cex.axis=0.7)
lines(x=c(mean(sub_1$text_counts),mean(sub_1$text_counts)),y=c(-0.5,0.6),col="red",lty=2)
plot(density(sub_2$text_counts),xlab = "",main = "Density of text counts when latent state is disease",cex.main=0.7,cex.lab=0.7,cex.axis=0.7)
lines(x=c(mean(sub_2$text_counts),mean(sub_2$text_counts)),y=c(-0.5,0.6),col="red",lty=2)

## when latent state is 2, the duration will be larger
plot(density(sub_1$duration),xlab = "",main = "Density of duration when latent state is nondisease",cex.main=0.7,cex.lab=0.7,cex.axis=0.7)
lines(x=c(mean(sub_1$duration),mean(sub_1$duration)),y=c(-0.5,0.6),col="red",lty=2)
plot(density(sub_2$duration),xlab = "",main = "Density of duration when latent state is disease",cex.main=0.7,cex.lab=0.7,cex.axis=0.7)
lines(x=c(mean(sub_2$duration),mean(sub_2$duration)),y=c(-0.5,0.6),col="red",lty=2)

plot(complete_data$z,xlim = c(0,200),xlab = "Day point",main = "Latent disease state plot",ylab="Latent disease status")
```

## missing data generation

```{r}
set.seed(1)
response_mcar=rbinom(T,size=1,prob = rtruncnorm(T,mean = 0.6,sd=0.1,a=0,b=1))
length(response_mcar[which(response_mcar==1)])/length(response_mcar)

set.seed(1)
z_resp_mar=2.5-0.3*complete_data$call_counts-0.4*complete_data$text_counts
pr_resp_mar=(1/(1+exp(-z_resp_mar)))
response_mar=rbinom(T,size=1,prob = pr_resp_mar)

length(response_mar[which(response_mar==1)])/length(response_mar)

set.seed(1)
z_resp_mnar=2.7-0.6*survey_outcome
pr_resp_mnar=(1/(1+exp(-z_resp_mnar)))
response_mnar=rbinom(T,size=1,prob = pr_resp_mnar)
length(response_mnar[which(response_mnar==1)])/length(response_mnar)


mcar_dataset=cbind(complete_data,response_mcar) %>% 
  mutate(
    call_counts=as.factor(call_counts),
    text_counts=as.factor(text_counts),
    duration=as.factor(duration),
    survey_outcome=as.factor(survey_outcome)
  )
mcar_dataset[which(response_mcar==0),4]=NA
as.data.frame(mcar_dataset)

mar_dataset=cbind(complete_data,response_mar)%>% 
  mutate(
    call_counts=as.factor(call_counts),
    text_counts=as.factor(text_counts),
    duration=as.factor(duration),
    survey_outcome=as.factor(survey_outcome)
  )
mar_dataset[which(response_mar==0),4]=NA
as.data.frame(mar_dataset)

mnar_dataset=cbind(complete_data,response_mnar)%>% 
  mutate(
    call_counts=as.factor(call_counts),
    text_counts=as.factor(text_counts),
    duration=as.factor(duration),
    survey_outcome=as.factor(survey_outcome)
  )
mnar_dataset[which(response_mnar==0),4]=NA
as.data.frame(mnar_dataset)

write.csv(mcar_dataset,"mcar_dataset")
write.csv(mar_dataset,"mar_dataset")
write.csv(mnar_dataset,"mnar_dataset")
write.csv(complete_data,"complete_data")
```

## impute missing value

#### MICE

```{r}
set.seed(1)
imputed_data_mcar <- mice(mcar_dataset[1:4], m=5, maxit = 50, method = 'polr', seed = 500)
summary(imputed_data_mcar)
imputed_data_mcar$imp$survey_outcome
completeData_mcar <- complete(imputed_data_mcar,2)

set.seed(1)
imputed_data_mar <- mice(mar_dataset[1:4], m=5, maxit = 50, method = 'polr', seed = 500)
completeData_mar <- complete(imputed_data_mar,2)

set.seed(1)
imputed_data_mnar <- mice(mcar_dataset[1:4], m=5, maxit = 50, method = 'polr', seed = 500)
completeData_mnar <- complete(imputed_data_mnar,2)

```

## mean
```{r}
mcar_dataset$imputed_survey_outcome=with(mcar_dataset,impute(survey_outcome,mean))
mar_dataset$imputed_survey_outcome=with(mar_dataset,impute(survey_outcome,mean))
mnar_dataset$imputed_survey_outcome=with(mnar_dataset,impute(survey_outcome,mean))
```

## forward
```{r}
mcar_dataset$imputed_survey_outcome_forward=LOCF(as.numeric(mcar_dataset$survey_outcome)+2)
mar_dataset$imputed_survey_outcome_forward=LOCF(as.numeric(mar_dataset$survey_outcome)+2)
mnar_dataset$imputed_survey_outcome_forward=LOCF(as.numeric(mnar_dataset$survey_outcome)+2)
```

## Missforest
```{r}
set.seed(1)
mcar_miss_impute=missForest(mcar_dataset)
mcar_dataset$imputed_survey_outcome_missforest=mcar_miss_impute$ximp$survey_outcome

set.seed(1)
mar_miss_impute=missForest(mar_dataset)
mar_dataset$imputed_survey_outcome_missforest=mar_miss_impute$ximp$survey_outcome

set.seed(1)
mnar_miss_impute=missForest(mnar_dataset)
mnar_dataset$imputed_survey_outcome_missforest=mnar_miss_impute$ximp$survey_outcome
```


